### ISSUE TITLE
Config loading is done after running 

### ISSUE THREAD

**Issue by ahmad-musleh** [oblivm/ObliVMGC#3]
https://github.com/oblivm/ObliVMGC/blob/72f54819e4b5cf8bc0a59457cf6cd2c47fbd5c82/java/com/oblivm/backend/util/EvaRunnable.java#L114-L115

Upon running I find that program is always stuck at connecting (always blocking), but when I interchange these lines the problem is mediated (although I'm facing another issue). I think loadConfig should be run before `run`. This would make it similar to 

https://github.com/oblivm/ObliVMGC/blob/72f54819e4b5cf8bc0a59457cf6cd2c47fbd5c82/java/com/oblivm/backend/util/GenRunnable.java#L106-L107

where config is loaded first. 

to produce this problem I just run 

`./runMill.sh`

provided in the main directory

**Comment by wangxiao1254** [comment]
Please take a look at this version https://github.com/wangxiao1254/FlexSC/blob/master/src/util/EvaRunnable.java

I believe the one in FlexSC runs fine.

**Comment by ahmad-musleh** [comment]
Yes. Config is set before running. Seems like it would run fine that way. Thank you.

I would like to ask if there is a specific purpose for having it this way here? I just want to make sure I'm not missing out on anything.

**Comment by wangxiao1254** [comment]
Well the goal was to avoid recompiling back and forth during the development and to gather all information in one file such that experience may be easier to do.

In our recent emp-toolkit (based on C++, much faster and supports malicious security), we use system argument instead.

Thanks,

Xiao

**Comment by ahmad-musleh** [comment]
oh alright. Will this be reflected on this repo ? (as in having system arguments used ? )

**Comment by wangxiao1254** [comment]
I don't think so, but pull requests are welcome.
